name: Build Beta

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Build main.py
      run: |
        python -m pip install --upgrade pip
        pip install PyInstaller
        pyinstaller --onefile --icon NONE main.py
        ls
        mv dist/main.exe dist/game.exe
    - name: Create beta release
      uses: marvinpinto/action-automatic-releases@v1.1.0
      env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "beta"
          prerelease: true
          title: "Basic Game BETA"
          files: |
            dist/game.exe
